name: golangci-lint
on:
  pull_request:
jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: [ '1.15', '1.14', '1.13', '1.12']
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}
      - name: lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.30
      - name: test
        run: go test ./pkg/smartsheet
      - name: coverage
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
